#!/usr/bin/env ruby

m = readlines.map { |e| e.hex }

loop do
    unless m[1] < 0
        print m[1].chr
        m[1] = -1
    end
    m[2] = (STDIN.getc || 256) if m[2] < 0
    a, b, c = m[m[0], 3]
    q = (m[c] = m[a] - m[b]) < 0 ? 6 : 3
    m[0] += q
end rescue 0
